services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/18/docker"
      - "./create_database_pg.ddl:/docker-entrypoint-initdb.d/init.sql"